import styles from "./styles.module.css"

export const rankData = {
	en: {
		landInfo: 'Land Information',
		unlockFeature: 'Additional Features',
		RankList: [
			{
				title: "IRON",
				playtime: "Default",
				ownerland: "1 Land Owner",
				l_avai: "3 Land Availability",
				supchunk: "1 Support Chunk",
				freechunk: "10 Free Chunk",
				chunklimit: "20 Chunk Limit",
				landmember: " 10 Land Member",
				landrole: "5 Land Role",
				description: "- Minespawner \n(Netherite Pickaxe + Silk Touch)",
				link: "#",
				cardColorClass: styles.iron, // Specific color class
			},
			{
				title: "BRONZE",
				playtime: "6 hours",
				ownerland: "1 Land Owner",
				l_avai: "4 Land Availability",
				supchunk: "2 Support Chunk",
				freechunk: "12 Free Chunk",
				chunklimit: "25 Chunk Limit",
				landmember: " 10 Land Member",
				landrole: "5 Land Role",
				description: "- Sit on sitable block\n - /lands inspect command",
				link: "#",
				cardColorClass: styles.bronze, // Specific color class
			},
			{
				title: "SILVER",
				playtime: "20 hours",
				ownerland: "1 Land Owner",
				l_avai: "5 Land Availability",
				supchunk: "3 Support Chunk",
				freechunk: "15 Free Chunk",
				chunklimit: "30 Chunk Limit",
				landmember: " 10 Land Member",
				landrole: "5 Land Role",
				description: "- /Sit command to sit",
				link: "#",
				cardColorClass: styles.silver, // Specific color class
			},
			,
			{
				title: "GOLD",
				playtime: "43 hours",
				ownerland: "2 Land Owner",
				l_avai: "6 Land Availability",
				supchunk: "4 Support Chunk",
				freechunk: "15 Free Chunk",
				chunklimit: "40 Chunk Limit",
				landmember: " 12 Land Member",
				landrole: "5 Land Role",
				description: "- /craft or /wb command to open workbench\n - Image Map 10\n - Chest Shop 10\n- Player Warp : 1 ",
				link: "#",
				cardColorClass: styles.gold, // Specific color class
			},
			,
			{
				title: "PLATINUM",
				playtime: "78 hours",
				ownerland: "2 Land Owner",
				l_avai: "7 Land Availability",
				supchunk: "5 Support Chunk",
				freechunk: "15 Free Chunk",
				chunklimit: "55 Chunk Limit",
				landmember: " 14 Land Member",
				landrole: "5 Land Role",
				description: "- /anvil command to open anvil\n - Elytraboost\n- Player Warp : 1",

				link: "#",
				cardColorClass: styles.platinum, // Specific color class
			},
			{
				title: "EMERALD",
				playtime: "131 hours",
				ownerland: "3 Land Owner",
				l_avai: "8 Land Availability",
				supchunk: "6 Support Chunk",
				freechunk: "15 Free Chunk",
				chunklimit: "70 Chunk Limit",
				landmember: " 16 Land Member",
				landrole: "5 Land Role",
				description: "- Create Nation\n - /bin or /dispose for clear you don't need\n - Open Shulker without placing\n- Player Warp : 2",
				link: "#",
				cardColorClass: styles.emerald, // Specific color class
			},
			{
				title: "DIAMOND",
				playtime: "214 hours",
				ownerland: "4 Land Owner",
				l_avai: "9 Land Availability",
				supchunk: "7 Support Chunk",
				freechunk: "15 Free Chunk",
				chunklimit: "90 Chunk Limit",
				landmember: " 18 Land Member",
				landrole: "5 Land Role",
				description: "- Head Shop /hdb and /hdb \nsearch[name]\n - Armor Stand Editing \n(Shift + Right-Click\n - Open enderchest /ec or /ender command\n- Player Warp : 2",
				link: "#",
				cardColorClass: styles.diamond, // Specific color class
			},
			{
				title: "ASTRAL",
				playtime: "354 hours",
				ownerland: "5 Land Owner",
				l_avai: "10 Land Availability",
				supchunk: "8 Support Chunk",
				freechunk: "15 Free Chunk",
				chunklimit: "150 Chunk Limit",
				landmember: " 20 Land Member",
				landrole: "5 Land Role",
				description: "- Mirror\n- Player Warp : 4",
				link: "#",
				cardColorClass: styles.astral, // Specific color class
			},
			{
				title: "COSMIC",
				playtime: "603 hours",
				ownerland: "7 Land Owner",
				l_avai: "12 Land Availability",
				supchunk: "10 Support Chunk",
				freechunk: "15 Free Chunk",
				chunklimit: "250 Chunk Limit",
				landmember: " 25 Land Member",
				landrole: "5 Land Role",
				description: "- Flight Charge\n- Player Warp : 6",
				link: "#",
				cardColorClass: styles.cosmic, // Specific color class
			},
			{
				title: "ETERNITY",
				playtime: "1080 hours",
				ownerland: "10 Land Owner",
				l_avai: "15 Land Availability",
				supchunk: "15 Support Chunk",
				freechunk: "15 Free Chunk",
				chunklimit: "400 Chunk Limit",
				landmember: " 40 Land Member",
				landrole: "5 Land Role",
				description: "- Early Access to new features\n- Player Warp : 8",
				link: "#",
				cardColorClass: styles.eternity, // Specific color class
			},
		],
		RankSupList: [
			{
			  title: "SUPPORTER I",
			  price: "199THB",
			  ownerland: "4 Land Owner",
			  l_avai: "9 Land Availability",
			  supchunk: "7 Support Chunk",
			  freechunk: "15 Free Chunk",
			  chunklimit: "90 Chunk Limit",
			  arealimit: "3 Area Limit",
			  landmember: "18 Land Member",
			  landrole: "6 Land Role",
			  description: "- Access Diamond Rank Features\n- /hat command\n - Player Market Capacity : 3\n- Player Market Time : 10 Days\n- Image Map : 10\n- Max Homes : 5\n- Chest Shop : 10\n- Player Warp : 2",
			  link: "#",
			  cardColorClass: styles.SupI,
			},
			{
			  title: "SUPPORTER II",
			  price: "399THB",
			  ownerland: "7 Land Owner",
			  l_avai: "12 Land Availability",
			  supchunk: "7 Support Chunk",
			  freechunk: "15 Free Chunk",
			  chunklimit: "90 Chunk Limit",
			  arealimit: "5 Area Limit",
			  landmember: "18 Land Member",
			  landrole: "6 Land Role",
			  description: "- Access Suppoerter I Features\n- Unlock all Pose /crawl, /bellyflop, /lay, /spin, /sit and sit on other player head\n - Player Market Capacity : 5\n- Player Market Time : 12 Days\n- Image Map : 15\n- Max Homes : 5\n- Chest Shop : 15\n- Player Warp : 4",
			  link: "#",
			  cardColorClass: styles.SupII,
			},
			{
			  title: "SUPPORTER III",
			  price: "799THB",
			  ownerland: "10 Land Owner",
			  l_avai: "15 Land Availability",
			  supchunk: "7 Support Chunk",
			  freechunk: "15 Free Chunk",
			  chunklimit: "90 Chunk Limit",
			  arealimit: "7 Area Limit",
			  landmember: "18 Land Member",
			  landrole: "7 Land Role",
			  description: "- Access Suppoerter I-II Features\n- Auto Tree Chopping Unlimited\n - Player Market Capacity : 10\n- Player Market Time : 15 Days\n- Image Map : 20\n- Max Homes : 7\n- Chest Shop : 15\n- Player Warp : 6",
			  link: "#",
			  cardColorClass: styles.SupIII,
			},
			{
			  title: "SUPPORTER IV",
			  price: "1,499THB",
			  ownerland: "15 Land Owner",
			  l_avai: "20 Land Availability",
			  supchunk: "15 Support Chunk",
			  freechunk: "15 Free Chunk",
			  chunklimit: "90 Chunk Limit",
			  arealimit: "10 Area Limit",
			  landmember: "18 Land Member",
			  landrole: "10 Land Role",
			  description: "- Access Suppoerter I-III\n- Early Access to new features\n- Buy/Sell in Player Shop using /ah [sell/buy][price] command\n- /tpignore command \n - Player Market Capacity : 15\n- Player Market Time : 20 Days\n- Image Map : 25\n- Max Homes : 10\n- Chest Shop : 20\n- Player Warp : 10",
			  link: "#",
			  cardColorClass: styles.SupIV,
			},
			{
			  title: "SUPPORTER V",
			  price: "2,999THB",
			  ownerland: "20 Land Owner",
			  l_avai: "30 Land Availability",
			  supchunk: "25 Support Chunk",
			  freechunk: "15 Free Chunk",
			  chunklimit: "90 Chunk Limit",
			  arealimit: "15 Area Limit",
			  landmember: "65 Land Member",
			  landrole: "15 Land Role",
			  description: "- Access Suppoerter I-IV\n- /ptime command  to change the time in the server(Personal)\n- /pweather command to change the season in the server(Personal)\n- /back command to teleport to the previous location.\n - Player Market Capacity : 30\n- Player Market Time : 30 Days\n- Image Map : 30\n- Max Homes : 15\n- Chest Shop : 30\n- Player Warp : 15",
			  link: "#",
			  cardColorClass: styles.SupV,
			},
		  ]
	},
	th: {
		landInfo: 'ข้อมูล Land',
		unlockFeature: 'คุณสมบัติเพิ่มเติม',
		RankList: [
			{
				title: "IRON",
				playtime: "Default",
				ownerland: "1 Land Owner",
				l_avai: "3 Land Availability",
				supchunk: "1 Support Chunk",
				freechunk: "10 Free Chunk",
				chunklimit: "20 Chunk Limit",
				landmember: " 10 Land Member",
				landrole: "5 Land Role",
				description: "- Minespawner \n(Netherite Pickaxe + Silk Touch)",
				link: "#",
				cardColorClass: styles.iron, // Specific color class
			},
			{
				title: "BRONZE",
				playtime: "6 hours",
				ownerland: "1 Land Owner",
				l_avai: "4 Land Availability",
				supchunk: "2 Support Chunk",
				freechunk: "12 Free Chunk",
				chunklimit: "25 Chunk Limit",
				landmember: " 10 Land Member",
				landrole: "5 Land Role",
				description: "- นั่งบนบล็อคนั่งได้\n - คำสั่ง /lands inspect",
				link: "#",
				cardColorClass: styles.bronze, // Specific color class
			},
			{
				title: "SILVER",
				playtime: "20 hours",
				ownerland: "1 Land Owner",
				l_avai: "5 Land Availability",
				supchunk: "3 Support Chunk",
				freechunk: "15 Free Chunk",
				chunklimit: "30 Chunk Limit",
				landmember: " 10 Land Member",
				landrole: "5 Land Role",
				description: "- คำสั่ง /Sit เพื่อนั่ง",
				link: "#",
				cardColorClass: styles.silver, // Specific color class
			},
			,
			{
				title: "GOLD",
				playtime: "43 hours",
				ownerland: "2 Land Owner",
				l_avai: "6 Land Availability",
				supchunk: "4 Support Chunk",
				freechunk: "15 Free Chunk",
				chunklimit: "40 Chunk Limit",
				landmember: " 12 Land Member",
				landrole: "5 Land Role",
				description: "- คำสั่ง /craft หริอ /wb เพื่อเปิดโต๊ะคราฟต์\n - Image Map 10\n - Chest Shop 10\n- Player Warp : 1 ",
				link: "#",
				cardColorClass: styles.gold, // Specific color class
			},
			,
			{
				title: "PLATINUM",
				playtime: "78 hours",
				ownerland: "2 Land Owner",
				l_avai: "7 Land Availability",
				supchunk: "5 Support Chunk",
				freechunk: "15 Free Chunk",
				chunklimit: "55 Chunk Limit",
				landmember: " 14 Land Member",
				landrole: "5 Land Role",
				description: "- คำสั่ง /anvil เพื่อเปิดทั่ง \n - Elytraboost\n- Player Warp : 1",

				link: "#",
				cardColorClass: styles.platinum, // Specific color class
			},
			{
				title: "EMERALD",
				playtime: "131 hours",
				ownerland: "3 Land Owner",
				l_avai: "8 Land Availability",
				supchunk: "6 Support Chunk",
				freechunk: "15 Free Chunk",
				chunklimit: "70 Chunk Limit",
				landmember: " 16 Land Member",
				landrole: "5 Land Role",
				description: "- สร้าง Nation ได้\n - คำสั่ง /bin หรือ /dispose เพื่อทิ้งไอเทมที่ไม่ต้องการ\n - เปิด Shulker ได้โดยไม่ต้องวาง\n- Player Warp : 2",
				link: "#",
				cardColorClass: styles.emerald, // Specific color class
			},
			{
				title: "DIAMOND",
				playtime: "214 hours",
				ownerland: "4 Land Owner",
				l_avai: "9 Land Availability",
				supchunk: "7 Support Chunk",
				freechunk: "15 Free Chunk",
				chunklimit: "90 Chunk Limit",
				landmember: " 18 Land Member",
				landrole: "5 Land Role",
				description: "- Head Shop /hdb และ /hdb \nsearch[name]\n - Armor Stand Editing \n(Shift + Right-Click\n - คำสั่งเปิด enderchest /ec หริอ /ender\n- Player Warp : 2",
				link: "#",
				cardColorClass: styles.diamond, // Specific color class
			},
			{
				title: "ASTRAL",
				playtime: "354 hours",
				ownerland: "5 Land Owner",
				l_avai: "10 Land Availability",
				supchunk: "8 Support Chunk",
				freechunk: "15 Free Chunk",
				chunklimit: "150 Chunk Limit",
				landmember: " 20 Land Member",
				landrole: "5 Land Role",
				description: "- Mirror\n- Player Warp : 4",
				link: "#",
				cardColorClass: styles.astral, // Specific color class
			},
			{
				title: "COSMIC",
				playtime: "603 hours",
				ownerland: "7 Land Owner",
				l_avai: "12 Land Availability",
				supchunk: "10 Support Chunk",
				freechunk: "15 Free Chunk",
				chunklimit: "250 Chunk Limit",
				landmember: " 25 Land Member",
				landrole: "5 Land Role",
				description: "- Flight Charge\n- Player Warp : 6",
				link: "#",
				cardColorClass: styles.cosmic, // Specific color class
			},
			{
				title: "ETERNITY",
				playtime: "1080 hours",
				ownerland: "10 Land Owner",
				l_avai: "15 Land Availability",
				supchunk: "15 Support Chunk",
				freechunk: "15 Free Chunk",
				chunklimit: "400 Chunk Limit",
				landmember: " 40 Land Member",
				landrole: "5 Land Role",
				description: "- Early Access เข้าถึงฟีเจอร์ใหม่ ๆ ได้ก่อนใคร\n- Player Warp : 8",
				link: "#",
				cardColorClass: styles.eternity, // Specific color class
			},
		],
		RankSupList: [
			{
			  title: "SUPPORTER I",
			  price: "199THB",
			  ownerland: "4 Land Owner",
			  l_avai: "9 Land Availability",
			  supchunk: "7 Support Chunk",
			  freechunk: "15 Free Chunk",
			  chunklimit: "90 Chunk Limit",
			  arealimit: "3 Area Limit",
			  landmember: "18 Land Member",
			  landrole: "6 Land Role",
			  description: "- เข้าถึงฟีเจอร์ Diamond Rank\n- /hat command\n - Player Market Capacity : 3\n- Player Market Time : 10 Days\n- Image Map : 10\n- Max Homes : 5\n- Chest Shop : 10\n- Player Warp : 2",
			  link: "#",
			  cardColorClass: styles.SupI,
			},
			{
			  title: "SUPPORTER II",
			  price: "399THB",
			  ownerland: "7 Land Owner",
			  l_avai: "12 Land Availability",
			  supchunk: "7 Support Chunk",
			  freechunk: "15 Free Chunk",
			  chunklimit: "90 Chunk Limit",
			  arealimit: "5 Area Limit",
			  landmember: "18 Land Member",
			  landrole: "6 Land Role",
			  description: "- เข้าถึงฟีเจอร์ Suppoerter I\n- ปลดล็อก Pose ทั้งหมด /crawl, /bellyflop, /lay, /spin, /sit และนั่งหัวผู้เล่นอื่นได้\n - Player Market Capacity : 5\n- Player Market Time : 12 Days\n- Image Map : 15\n- Max Homes : 5\n- Chest Shop : 15\n- Player Warp : 4",
			  link: "#",
			  cardColorClass: styles.SupII,
			},
			{
			  title: "SUPPORTER III",
			  price: "799THB",
			  ownerland: "10 Land Owner",
			  l_avai: "15 Land Availability",
			  supchunk: "7 Support Chunk",
			  freechunk: "15 Free Chunk",
			  chunklimit: "90 Chunk Limit",
			  arealimit: "7 Area Limit",
			  landmember: "18 Land Member",
			  landrole: "7 Land Role",
			  description: "- เข้าถึงฟีเจอร์ Suppoerter I-II\n- Auto Tree Chopping ไม่จำกัด\n - Player Market Capacity : 10\n- Player Market Time : 15 Days\n- Image Map : 20\n- Max Homes : 7\n- Chest Shop : 15\n- Player Warp : 6",
			  link: "#",
			  cardColorClass: styles.SupIII,
			},
			{
			  title: "SUPPORTER IV",
			  price: "1,499THB",
			  ownerland: "15 Land Owner",
			  l_avai: "20 Land Availability",
			  supchunk: "15 Support Chunk",
			  freechunk: "15 Free Chunk",
			  chunklimit: "90 Chunk Limit",
			  arealimit: "10 Area Limit",
			  landmember: "18 Land Member",
			  landrole: "10 Land Role",
			  description: "- เข้าถึงฟีเจอร์ Suppoerter I-III\n- Early Access เข้าถึงฟีเจอร์ใหม่ ๆ ได้ก่อนใคร\n- Buy/Sell ใน Player Shop โดยใช้คำสั่ง /ah [sell/buy][price]\n- คำสั่ง /tpignore\n - Player Market Capacity : 15\n- Player Market Time : 20 Days\n- Image Map : 25\n- Max Homes : 10\n- Chest Shop : 20\n- Player Warp : 10",
			  link: "#",
			  cardColorClass: styles.SupIV,
			},
			{
			  title: "SUPPORTER V",
			  price: "2,999THB",
			  ownerland: "20 Land Owner",
			  l_avai: "30 Land Availability",
			  supchunk: "25 Support Chunk",
			  freechunk: "15 Free Chunk",
			  chunklimit: "90 Chunk Limit",
			  arealimit: "15 Area Limit",
			  landmember: "65 Land Member",
			  landrole: "15 Land Role",
			  description: "- เข้าถึงฟีเจอร์ Suppoerter I-IV\n- คำสั่ง /ptime เพื่อเปลี่ยนเวลาในเกม (ส่วนบุคคล)\n- คำสั่ง /pweather เพื่อเปลี่ยนสภาพอากาศในเกม(ส่วนบุคคล)\n- คำสั่ง /back เพื่อกลับไปตำแหน่งก่อนหน้า\n - Player Market Capacity : 30\n- Player Market Time : 30 Days\n- Image Map : 30\n- Max Homes : 15\n- Chest Shop : 30\n- Player Warp : 15",
			  link: "#",
			  cardColorClass: styles.SupV,
			},
		  ]
	}
}