// src/components/enchantment/th/vanillaEnchantments.js
const vanillaEnchantments = {
  vanilla: {
    Armor: [
      {
        name: "Protection",
        maxLevel: 4,
        description: "ลดความเสียหายที่ได้รับลง %placeholder% % ",
        placeholder: "%level% * 4",
        conflict: ["Fire Protection", "Blast Protection", "Projectile Protection"],
      },
      {
        name: "Fire Protection",
        maxLevel: 4,
        description: "ลดความเสียหายจากไฟลง %damage% % และลดระยะเวลาการเผาไหม้ลง %time% % ",
        placeholder: { damage: "%level% * 8", time: "%level% * 15" },
        conflict: ["Protection", "Blast Protection", "Projectile Protection"],
      },
      {
        name: "Feather Falling",
        maxLevel: 4,
        description: "ลดความเสียหายจากการตกลง %placeholder% % ",
        placeholder: "%level% * 12",
        conflict: [],
      },
      {
        name: "Blast Protection",
        maxLevel: 4,
        description: "ลดความเสียหายจากระเบิดลง %damage% % และลดแรงกระแทกจากระเบิดลง %knockback%",
        placeholder: { damage: "%level% * 8", knockback: "%level% * 15" },
        conflict: ["Protection", "Fire Protection", "Projectile Protection"],
      },
      {
        name: "Projectile Protection",
        maxLevel: 4,
        description: "ลดความเสียหายจากสิ่งที่ยิงมาลง %placeholder% % ",
        placeholder: "%level% * 8",
        conflict: ["Protection", "Fire Protection", "Blast Protection"],
      },
      {
        name: "Respiration",
        maxLevel: 3,
        description: "ยืดเวลาการหายใจใต้น้ำเพิ่ม %seconds% วินาที และมีโอกาส %chance% % ที่จะไม่ได้รับความเสียหายจากการจมน้ำ",
        placeholder: { seconds: "15 * %level%", chance: "%level% / (%level% + 1)" },
        conflict: [],
      },
      {
        name: "Aqua Affinity",
        maxLevel: 1,
        description: "ขจัดโทษความเร็วในการขุดใต้น้ำ",
        placeholder: "-",
        conflict: [],
      },
      {
        name: "Thorns",
        maxLevel: 3,
        description: "มีโอกาส %placeholder% %  ที่จะสะท้อนความเสียหายบางส่วนกลับไปยังผู้โจมตี",
        placeholder: "%level% * 15",
        conflict: [],
      },
      {
        name: "Depth Strider",
        maxLevel: 3,
        description: "ลดการชะลอการเคลื่อนไหวใต้น้ำลง %placeholder% % ",
        placeholder: "%level% * 33.333333",
        conflict: ["Frost Walker"],
      },
      {
        name: "Frost Walker",
        maxLevel: 2,
        description: "เปลี่ยนน้ำรอบตัวผู้เล่นในรัศมี %placeholder% %  บล็อกให้เป็นน้ำแข็ง",
        placeholder: "%level% + 2",
        conflict: ["Depth Strider"],
      },
      {
        name: "Soul Speed",
        maxLevel: 3,
        description: "เพิ่มความเร็วในการเดินบนทรายวิญญาณและดินวิญญาณขึ้น %placeholder% % ",
        placeholder: "(%level% * 0.105) + 1.3",
        conflict: [],
      },
      {
        name: "Swift Sneak",
        maxLevel: 4,
        description: "ลดการชะลอการเคลื่อนไหวเมื่อหมอบลง %placeholder% % ",
        placeholder: "min(%level% * 15, 100)",
        conflict: [],
      },
    ],
    Weapon: [
      {
        name: "Sharpness",
        maxLevel: 20,
        description: "เพิ่มความเสียหายจากการโจมตีระยะประชิด %placeholder% % ",
        placeholder: "0.5 * %level% + 1",
        conflict: ["Smite", "Bane of Arthropods"],
      },
      {
        name: "Smite",
        maxLevel: 6,
        description: "เพิ่มความเสียหายต่อม็อบซอมบี้ %placeholder% % ",
        placeholder: "2.5 * %level%",
        conflict: ["Sharpness", "Bane of Arthropods"],
      },
      {
        name: "Bane of Arthropods",
        maxLevel: 6,
        description: "เพิ่มความเสียหายต่อม็อบแมง %damage% % และให้สถานะช้าลงสูงสุด %seconds% วินาที",
        placeholder: { damage: "2.5 * %level%", seconds: "0.5 * %level%" },
        conflict: ["Sharpness", "Smite"],
      },
      {
        name: "Knockback",
        maxLevel: 5,
        description: "เพิ่มแรงกระแทกจากการโจมตี %placeholder% % ",
        placeholder: "%level% * 85 + 20",
        conflict: [],
      },
      {
        name: "Fire Aspect",
        maxLevel: 4,
        description: "ทำให้ศัตรูติดไฟ สร้างความเสียหายต่อเนื่อง",
        placeholder: "-",
        conflict: [],
      },
      {
        name: "Looting",
        maxLevel: 3,
        description: "เพิ่มจำนวนไอเทมที่ดรอปทั่วไป %common% และโอกาสได้ไอเทมพิเศษ %rare%",
        placeholder: { common: "%level%", rare: "%level%" },
        conflict: [],
      },
      {
        name: "Sweeping Edge",
        maxLevel: 5,
        description: "เพิ่มความเสียหายจากการโจมตีแบบกวาด %placeholder% % ",
        placeholder: "%level% / (%level% + 1)",
        conflict: [],
      },
    ],
    Tool: [
      {
        name: "Efficiency",
        maxLevel: 10,
        description: "เพิ่มความเร็วในการขุด %placeholder% % ",
        placeholder: "20 + 5 * %level%",
        conflict: [],
      },
      {
        name: "Silk Touch",
        maxLevel: 1,
        description: "ทำให้บล็อกที่ขุดดรอปเป็นบล็อกเดิม",
        placeholder: "-",
        conflict: ["Fortune"],
      },
      {
        name: "Unbreaking",
        maxLevel: 7,
        description: "เพิ่มความทนทานของไอเทม %placeholder% % ",
        placeholder: "%level% + 1",
        conflict: [],
      },
      {
        name: "Fortune",
        maxLevel: 4,
        description: "เพิ่มโอกาสดรอปไอเทมจากบล็อกบางชนิด %placeholder% % ",
        placeholder: "ceil(((1 / (%level% + 2)) + ((%level% + 1) / 2)) * 100 - 100)",
        conflict: ["Silk Touch"],
      },
    ],
    Bow: [
      {
        name: "Power",
        maxLevel: 8,
        description: "เพิ่มความเสียหายของลูกธนู %placeholder% % ",
        placeholder: "25 * (%level% + 1)",
        conflict: [],
      },
      {
        name: "Punch",
        maxLevel: 5,
        description: "เพิ่มแรงกระแทกของลูกธนู %placeholder% %  บล็อก",
        placeholder: "3 * %level%",
        conflict: [],
      },
      {
        name: "Flame",
        maxLevel: 1,
        description: "ลูกธนูทำให้เป้าหมายติดไฟ สร้างความเสียหายจากไฟ 5 หน่วย",
        placeholder: "-",
        conflict: [],
      },
      {
        name: "Infinity",
        maxLevel: 1,
        description: "ป้องกันการใช้ลูกธนูธรรมดาเมื่อยิง ไม่ขัดแย้งกับ Mending",
        placeholder: "-",
        conflict: [],
      },
    ],
    FishingRod: [
      {
        name: "Luck of the Sea",
        maxLevel: 3,
        description: "เพิ่มโอกาสได้ของรางวัลจากการตกปลา %placeholder% % ",
        placeholder: "2 * %level%",
        conflict: [],
      },
      {
        name: "Lure",
        maxLevel: 4,
        description: "ลดเวลารอในการตกปลา %placeholder% %  วินาที",
        placeholder: "%level% * 5",
        conflict: [],
      },
    ],
    Trident: [
      {
        name: "Loyalty",
        maxLevel: 3,
        description: "ทำให้ตรีศูลกลับมาหลังจากขว้าง",
        placeholder: "-",
        conflict: ["Riptide"],
      },
      {
        name: "Impaling",
        maxLevel: 5,
        description: "เพิ่มความเสียหายต่อม็อบในน้ำ %placeholder% % ",
        placeholder: "%level% * 2.5",
        conflict: [],
      },
      {
        name: "Riptide",
        maxLevel: 3,
        description: "ขว้างตรีศูลเพื่อพุ่งตัวผู้เล่นเมื่ออยู่ในน้ำหรือฝนตก",
        placeholder: "-",
        conflict: ["Loyalty", "Channeling"],
      },
      {
        name: "Channeling",
        maxLevel: 1,
        description: "เรียกฟ้าผ่าลงที่ตำแหน่งที่ตรีศูลลงในช่วงพายุฝน",
        placeholder: "-",
        conflict: ["Riptide"],
      },
    ],
    Crossbow: [
      {
        name: "Multishot",
        maxLevel: 1,
        description: "ยิงลูกธนู 3 ลูกพร้อมกัน",
        placeholder: "-",
        conflict: ["Piercing"],
      },
      {
        name: "Quick Charge",
        maxLevel: 5,
        description: "ลดเวลาการชาร์จหน้าไม้ %placeholder% %  วินาที",
        placeholder: "%level% * 0.25",
        conflict: [],
      },
      {
        name: "Piercing",
        maxLevel: 4,
        description: "ลูกธนูทะลุผ่านสิ่งมีชีวิต %placeholder% %  ตัว",
        placeholder: "%level% + 1",
        conflict: ["Multishot"],
      },
    ],
    Special: [
      {
        name: "Mending",
        maxLevel: 1,
        description: "ซ่อมแซมไอเทมเมื่อได้รับ XP ไม่ขัดแย้งกับ Infinity",
        placeholder: "-",
        conflict: [],
      },
      {
        name: "Curse of Binding",
        maxLevel: 1,
        description: "ไม่สามารถถอดไอเทมออกจากช่องเกราะได้",
        placeholder: "-",
        notes: "คำสาป",
        conflict: [],
      },
      {
        name: "Curse of Vanishing",
        maxLevel: 1,
        description: "ไอเทมถูกทำลายเมื่อตาย",
        placeholder: "-",
        notes: "คำสาป",
        conflict: [],
      },
    ],
  },
};

export default vanillaEnchantments;